apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pakpipeline
  namespace: default
spec:
  params:
    - default: deployer
      name: name
      type: string
  tasks:
    - name: ibm-pak
      params:
        - name: SCRIPT
          value: |-
            echo "$(params.name)"
            oc ibm-pak help
      taskRef:
        kind: Task
        name: ibm-pak-0.2
